spring:
  application:
    name: config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/AntiLogi/spring-clound-config
          search-paths: respo
          username: AntiLogi
          password: xb23080822

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/